name: GCP Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy GCP Infra
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            jq \
            curl \
            unzip \
            gnupg \
            lsb-release \
            software-properties-common   

      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'    

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: |
          cd gcp/infra
          terraform init

      - name: Terraform Plan
        run: |
          cd gcp/infra
          terraform plan -var-file=terraform.tfvars.json 2>&1 | tee terraform_plan.log

      - name: Terraform Apply
        run: |
          cd gcp/infra
          terraform apply -var-file=terraform.tfvars.json -auto-approve 2>&1 | tee terraform_apply.log

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-logs
          path: |
            gcp/infra/terraform_plan.log
            gcp/infra/terraform_apply.log

      - name: Get Outputs
        id: get_outputs
        run: |
          cd gcp/infra
          APP_URL=$(terraform output -raw app_url)
          TEXT_TO_TEST=$(terraform output -raw text_to_test)
          APP_URL=$(terraform output -raw app_url)
          echo "APP_URL=$APP_URL" >> $GITHUB_ENV
          echo $APP_URL
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo $S3_BUCKET
          echo "TEXT_TO_TEST=$TEXT_TO_TEST" >> $GITHUB_ENV
          echo $S3_BUCKET          

      - name: AI Powered Web Test
        run: |
          echo "Testing the URL from terraform output: $APP_URL"
        env:
          APP_URL: ${{ env.APP_URL }}
          TEXT_TO_TEST: ${{ env.TEXT_TO_TEST }}
          S3_BUCKET: ${{ env.S3_BUCKET }}
